from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('minhas_listas/', views.minhas_listas, name='minhas_listas'),
    path('cadastro/', views.cadastro, name='cadastro'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('perfil/', views.perfil, name='perfil'),
    path('csrf/', views.csrf, name='csrf'),
    path('create_shopping_list/', views.create_shopping_list, name='create_shopping_list'),
    path('get_shopping_list/<int:list_id>/', views.get_shopping_list, name='get_shopping_list'),
    path('update_shopping_list/<int:list_id>/', views.update_shopping_list, name='update_shopping_list'),
    path('delete_shopping_list/<int:list_id>/', views.delete_shopping_list, name='delete_shopping_list'),
    path('search_users/', views.search_users, name='search_users'),
    path('send_friend_request/', views.send_friend_request, name='send_friend_request'),
    path('accept_friend_request/<int:request_id>/', views.accept_friend_request, name='accept_friend_request'),
    path('reject_friend_request/<int:request_id>/', views.reject_friend_request, name='reject_friend_request'),
    path('search/', views.search, name='search'),
    path('add_item_to_list/<int:list_id>/', views.add_item_to_list, name='add_item_to_list'),
    path('update_item/<int:item_id>/', views.update_item, name='update_item'),
    path('delete_item/<int:item_id>/', views.delete_item, name='delete_item'),
    path('get_item/<int:item_id>/', views.get_item, name='get_item'),
    path('get_recent_activities/', views.get_recent_activities, name='get_recent_activities'),
    path('share_list/<int:list_id>/', views.share_list, name='share_list'),
    path('get_share_link/<int:list_id>/', views.get_share_link, name='get_share_link'),
    path('l/<uuid:share_id>/', views.shared_list_view, name='shared_list_view'),
    path('update_share_permissions/<int:list_id>/', views.update_share_permissions, name='update_share_permissions'),
    path('update_share_settings/<int:list_id>/', views.update_share_settings, name='update_share_settings'),
    path('remove_shared_list/<int:list_id>/', views.remove_shared_list, name='remove_shared_list'),
    path('excluir_amizade/<int:amizade_id>/', views.excluir_amizade, name='excluir_amizade'),
]